import_energy_data:
  name: Obtener nuevos datos de energía
  description: Obtiene nuevos datos de energía desde el último día hasta dos menos del actual. Se ejecuta automáticamnete todos los días a las 7:05.
force_import_energy_data:
  name: Forzar obtención de datos de energía
  description: Obtiene los datos de consumo y coste de los últimos 2 años y los sobreescribe (los datos existentes de más de 2 años se mantienen). Regenera todas las estadísticas y facturas.
reprocess_energy_data:
  name: Reprocesar datos de energía
  description: Regenera las estadísticas del panel de energía y las facturas.
